// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roboception/msgs/pose_stamped.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "roboception/msgs/pose_stamped.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace roboception {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* PoseStamped_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PoseStamped_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto() {
  protobuf_AddDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "roboception/msgs/pose_stamped.proto");
  GOOGLE_CHECK(file != NULL);
  PoseStamped_descriptor_ = file->message_type(0);
  static const int PoseStamped_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseStamped, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseStamped, pose_),
  };
  PoseStamped_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PoseStamped_descriptor_,
      PoseStamped::default_instance_,
      PoseStamped_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseStamped, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PoseStamped, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PoseStamped));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PoseStamped_descriptor_, &PoseStamped::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_roboception_2fmsgs_2fpose_5fstamped_2eproto() {
  delete PoseStamped::default_instance_;
  delete PoseStamped_reflection_;
}

void protobuf_AddDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::roboception::msgs::protobuf_AddDesc_roboception_2fmsgs_2ftime_2eproto();
  ::roboception::msgs::protobuf_AddDesc_roboception_2fmsgs_2fpose_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n#roboception/msgs/pose_stamped.proto\022\020r"
    "oboception.msgs\032\033roboception/msgs/time.p"
    "roto\032\033roboception/msgs/pose.proto\"^\n\013Pos"
    "eStamped\022)\n\ttimestamp\030\001 \001(\0132\026.roboceptio"
    "n.msgs.Time\022$\n\004pose\030\002 \001(\0132\026.roboception."
    "msgs.PoseB)\n\024com.roboception.msgsB\021PoseS"
    "tampedProtos", 252);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "roboception/msgs/pose_stamped.proto", &protobuf_RegisterTypes);
  PoseStamped::default_instance_ = new PoseStamped();
  PoseStamped::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_roboception_2fmsgs_2fpose_5fstamped_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_roboception_2fmsgs_2fpose_5fstamped_2eproto {
  StaticDescriptorInitializer_roboception_2fmsgs_2fpose_5fstamped_2eproto() {
    protobuf_AddDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto();
  }
} static_descriptor_initializer_roboception_2fmsgs_2fpose_5fstamped_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PoseStamped::kTimestampFieldNumber;
const int PoseStamped::kPoseFieldNumber;
#endif  // !_MSC_VER

PoseStamped::PoseStamped()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PoseStamped::InitAsDefaultInstance() {
  timestamp_ = const_cast< ::roboception::msgs::Time*>(&::roboception::msgs::Time::default_instance());
  pose_ = const_cast< ::roboception::msgs::Pose*>(&::roboception::msgs::Pose::default_instance());
}

PoseStamped::PoseStamped(const PoseStamped& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PoseStamped::SharedCtor() {
  _cached_size_ = 0;
  timestamp_ = NULL;
  pose_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PoseStamped::~PoseStamped() {
  SharedDtor();
}

void PoseStamped::SharedDtor() {
  if (this != default_instance_) {
    delete timestamp_;
    delete pose_;
  }
}

void PoseStamped::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PoseStamped::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PoseStamped_descriptor_;
}

const PoseStamped& PoseStamped::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto();
  return *default_instance_;
}

PoseStamped* PoseStamped::default_instance_ = NULL;

PoseStamped* PoseStamped::New() const {
  return new PoseStamped;
}

void PoseStamped::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_timestamp()) {
      if (timestamp_ != NULL) timestamp_->::roboception::msgs::Time::Clear();
    }
    if (has_pose()) {
      if (pose_ != NULL) pose_->::roboception::msgs::Pose::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PoseStamped::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .roboception.msgs.Time timestamp = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_timestamp()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_pose;
        break;
      }

      // optional .roboception.msgs.Pose pose = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_pose:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_pose()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PoseStamped::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .roboception.msgs.Time timestamp = 1;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->timestamp(), output);
  }

  // optional .roboception.msgs.Pose pose = 2;
  if (has_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->pose(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PoseStamped::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .roboception.msgs.Time timestamp = 1;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->timestamp(), target);
  }

  // optional .roboception.msgs.Pose pose = 2;
  if (has_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->pose(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PoseStamped::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .roboception.msgs.Time timestamp = 1;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->timestamp());
    }

    // optional .roboception.msgs.Pose pose = 2;
    if (has_pose()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->pose());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PoseStamped::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PoseStamped* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PoseStamped*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PoseStamped::MergeFrom(const PoseStamped& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_timestamp()) {
      mutable_timestamp()->::roboception::msgs::Time::MergeFrom(from.timestamp());
    }
    if (from.has_pose()) {
      mutable_pose()->::roboception::msgs::Pose::MergeFrom(from.pose());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PoseStamped::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PoseStamped::CopyFrom(const PoseStamped& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PoseStamped::IsInitialized() const {

  return true;
}

void PoseStamped::Swap(PoseStamped* other) {
  if (other != this) {
    std::swap(timestamp_, other->timestamp_);
    std::swap(pose_, other->pose_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PoseStamped::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PoseStamped_descriptor_;
  metadata.reflection = PoseStamped_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace roboception

// @@protoc_insertion_point(global_scope)
