// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roboception/msgs/pose.proto

#ifndef PROTOBUF_roboception_2fmsgs_2fpose_2eproto__INCLUDED
#define PROTOBUF_roboception_2fmsgs_2fpose_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "roboception/msgs/vector3d.pb.h"
#include "roboception/msgs/quaternion.pb.h"
// @@protoc_insertion_point(includes)

namespace roboception {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_roboception_2fmsgs_2fpose_2eproto();
void protobuf_AssignDesc_roboception_2fmsgs_2fpose_2eproto();
void protobuf_ShutdownFile_roboception_2fmsgs_2fpose_2eproto();

class Pose;

// ===================================================================

class Pose : public ::google::protobuf::Message {
 public:
  Pose();
  virtual ~Pose();

  Pose(const Pose& from);

  inline Pose& operator=(const Pose& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pose& default_instance();

  void Swap(Pose* other);

  // implements Message ----------------------------------------------

  Pose* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pose& from);
  void MergeFrom(const Pose& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .roboception.msgs.Vector3d position = 1;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 1;
  inline const ::roboception::msgs::Vector3d& position() const;
  inline ::roboception::msgs::Vector3d* mutable_position();
  inline ::roboception::msgs::Vector3d* release_position();
  inline void set_allocated_position(::roboception::msgs::Vector3d* position);

  // optional .roboception.msgs.Quaternion orientation = 2;
  inline bool has_orientation() const;
  inline void clear_orientation();
  static const int kOrientationFieldNumber = 2;
  inline const ::roboception::msgs::Quaternion& orientation() const;
  inline ::roboception::msgs::Quaternion* mutable_orientation();
  inline ::roboception::msgs::Quaternion* release_orientation();
  inline void set_allocated_orientation(::roboception::msgs::Quaternion* orientation);

  // repeated double covariance = 3 [packed = true];
  inline int covariance_size() const;
  inline void clear_covariance();
  static const int kCovarianceFieldNumber = 3;
  inline double covariance(int index) const;
  inline void set_covariance(int index, double value);
  inline void add_covariance(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      covariance() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_covariance();

  // @@protoc_insertion_point(class_scope:roboception.msgs.Pose)
 private:
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_orientation();
  inline void clear_has_orientation();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::roboception::msgs::Vector3d* position_;
  ::roboception::msgs::Quaternion* orientation_;
  ::google::protobuf::RepeatedField< double > covariance_;
  mutable int _covariance_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_roboception_2fmsgs_2fpose_2eproto();
  friend void protobuf_AssignDesc_roboception_2fmsgs_2fpose_2eproto();
  friend void protobuf_ShutdownFile_roboception_2fmsgs_2fpose_2eproto();

  void InitAsDefaultInstance();
  static Pose* default_instance_;
};
// ===================================================================


// ===================================================================

// Pose

// optional .roboception.msgs.Vector3d position = 1;
inline bool Pose::has_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pose::set_has_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pose::clear_has_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pose::clear_position() {
  if (position_ != NULL) position_->::roboception::msgs::Vector3d::Clear();
  clear_has_position();
}
inline const ::roboception::msgs::Vector3d& Pose::position() const {
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
inline ::roboception::msgs::Vector3d* Pose::mutable_position() {
  set_has_position();
  if (position_ == NULL) position_ = new ::roboception::msgs::Vector3d;
  return position_;
}
inline ::roboception::msgs::Vector3d* Pose::release_position() {
  clear_has_position();
  ::roboception::msgs::Vector3d* temp = position_;
  position_ = NULL;
  return temp;
}
inline void Pose::set_allocated_position(::roboception::msgs::Vector3d* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
}

// optional .roboception.msgs.Quaternion orientation = 2;
inline bool Pose::has_orientation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Pose::set_has_orientation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Pose::clear_has_orientation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Pose::clear_orientation() {
  if (orientation_ != NULL) orientation_->::roboception::msgs::Quaternion::Clear();
  clear_has_orientation();
}
inline const ::roboception::msgs::Quaternion& Pose::orientation() const {
  return orientation_ != NULL ? *orientation_ : *default_instance_->orientation_;
}
inline ::roboception::msgs::Quaternion* Pose::mutable_orientation() {
  set_has_orientation();
  if (orientation_ == NULL) orientation_ = new ::roboception::msgs::Quaternion;
  return orientation_;
}
inline ::roboception::msgs::Quaternion* Pose::release_orientation() {
  clear_has_orientation();
  ::roboception::msgs::Quaternion* temp = orientation_;
  orientation_ = NULL;
  return temp;
}
inline void Pose::set_allocated_orientation(::roboception::msgs::Quaternion* orientation) {
  delete orientation_;
  orientation_ = orientation;
  if (orientation) {
    set_has_orientation();
  } else {
    clear_has_orientation();
  }
}

// repeated double covariance = 3 [packed = true];
inline int Pose::covariance_size() const {
  return covariance_.size();
}
inline void Pose::clear_covariance() {
  covariance_.Clear();
}
inline double Pose::covariance(int index) const {
  return covariance_.Get(index);
}
inline void Pose::set_covariance(int index, double value) {
  covariance_.Set(index, value);
}
inline void Pose::add_covariance(double value) {
  covariance_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
Pose::covariance() const {
  return covariance_;
}
inline ::google::protobuf::RepeatedField< double >*
Pose::mutable_covariance() {
  return &covariance_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace roboception

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_roboception_2fmsgs_2fpose_2eproto__INCLUDED
