// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roboception/msgs/pose_stamped.proto

#ifndef PROTOBUF_roboception_2fmsgs_2fpose_5fstamped_2eproto__INCLUDED
#define PROTOBUF_roboception_2fmsgs_2fpose_5fstamped_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "roboception/msgs/time.pb.h"
#include "roboception/msgs/pose.pb.h"
// @@protoc_insertion_point(includes)

namespace roboception {
namespace msgs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto();
void protobuf_AssignDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto();
void protobuf_ShutdownFile_roboception_2fmsgs_2fpose_5fstamped_2eproto();

class PoseStamped;

// ===================================================================

class PoseStamped : public ::google::protobuf::Message {
 public:
  PoseStamped();
  virtual ~PoseStamped();

  PoseStamped(const PoseStamped& from);

  inline PoseStamped& operator=(const PoseStamped& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PoseStamped& default_instance();

  void Swap(PoseStamped* other);

  // implements Message ----------------------------------------------

  PoseStamped* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PoseStamped& from);
  void MergeFrom(const PoseStamped& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .roboception.msgs.Time time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline const ::roboception::msgs::Time& time() const;
  inline ::roboception::msgs::Time* mutable_time();
  inline ::roboception::msgs::Time* release_time();
  inline void set_allocated_time(::roboception::msgs::Time* time);

  // optional .roboception.msgs.Pose pose = 2;
  inline bool has_pose() const;
  inline void clear_pose();
  static const int kPoseFieldNumber = 2;
  inline const ::roboception::msgs::Pose& pose() const;
  inline ::roboception::msgs::Pose* mutable_pose();
  inline ::roboception::msgs::Pose* release_pose();
  inline void set_allocated_pose(::roboception::msgs::Pose* pose);

  // repeated double covariance = 3 [packed = true];
  inline int covariance_size() const;
  inline void clear_covariance();
  static const int kCovarianceFieldNumber = 3;
  inline double covariance(int index) const;
  inline void set_covariance(int index, double value);
  inline void add_covariance(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      covariance() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_covariance();

  // @@protoc_insertion_point(class_scope:roboception.msgs.PoseStamped)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_pose();
  inline void clear_has_pose();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::roboception::msgs::Time* time_;
  ::roboception::msgs::Pose* pose_;
  ::google::protobuf::RepeatedField< double > covariance_;
  mutable int _covariance_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto();
  friend void protobuf_AssignDesc_roboception_2fmsgs_2fpose_5fstamped_2eproto();
  friend void protobuf_ShutdownFile_roboception_2fmsgs_2fpose_5fstamped_2eproto();

  void InitAsDefaultInstance();
  static PoseStamped* default_instance_;
};
// ===================================================================


// ===================================================================

// PoseStamped

// optional .roboception.msgs.Time time = 1;
inline bool PoseStamped::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PoseStamped::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PoseStamped::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PoseStamped::clear_time() {
  if (time_ != NULL) time_->::roboception::msgs::Time::Clear();
  clear_has_time();
}
inline const ::roboception::msgs::Time& PoseStamped::time() const {
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
inline ::roboception::msgs::Time* PoseStamped::mutable_time() {
  set_has_time();
  if (time_ == NULL) time_ = new ::roboception::msgs::Time;
  return time_;
}
inline ::roboception::msgs::Time* PoseStamped::release_time() {
  clear_has_time();
  ::roboception::msgs::Time* temp = time_;
  time_ = NULL;
  return temp;
}
inline void PoseStamped::set_allocated_time(::roboception::msgs::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
}

// optional .roboception.msgs.Pose pose = 2;
inline bool PoseStamped::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PoseStamped::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PoseStamped::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PoseStamped::clear_pose() {
  if (pose_ != NULL) pose_->::roboception::msgs::Pose::Clear();
  clear_has_pose();
}
inline const ::roboception::msgs::Pose& PoseStamped::pose() const {
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::roboception::msgs::Pose* PoseStamped::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) pose_ = new ::roboception::msgs::Pose;
  return pose_;
}
inline ::roboception::msgs::Pose* PoseStamped::release_pose() {
  clear_has_pose();
  ::roboception::msgs::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void PoseStamped::set_allocated_pose(::roboception::msgs::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
}

// repeated double covariance = 3 [packed = true];
inline int PoseStamped::covariance_size() const {
  return covariance_.size();
}
inline void PoseStamped::clear_covariance() {
  covariance_.Clear();
}
inline double PoseStamped::covariance(int index) const {
  return covariance_.Get(index);
}
inline void PoseStamped::set_covariance(int index, double value) {
  covariance_.Set(index, value);
}
inline void PoseStamped::add_covariance(double value) {
  covariance_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
PoseStamped::covariance() const {
  return covariance_;
}
inline ::google::protobuf::RepeatedField< double >*
PoseStamped::mutable_covariance() {
  return &covariance_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace roboception

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_roboception_2fmsgs_2fpose_5fstamped_2eproto__INCLUDED
